name: rpg_server
description: Server for Online RPG.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  socket_io: ^1.0.1

dev_dependencies:
  build_runner: ">=1.6.2 <3.0.0"
  build_web_compilers: ">=2.12.0 <4.0.0"